services:
  - type: web
    name: makirimay-backend
    env: python
    plan: free
    buildCommand: pip install -r app/back/requirements.txt
    startCommand: gunicorn app.back.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
